import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'u0165547' at '7/28/16 9:20 AM' with Gradle 2.13
 *
 * @author u0165547, @date 7/28/16 9:20 AM
 */
public class LibraryTest {
   /* @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }*/
}
