# github.com/go-task/task

version: '2'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  
  clean:
    cmds:
      - rm -rf target mlib mods
    silent: true
